dist: xenial
language: ruby
rvm:
- 2.5
before_install: |
  { echo "source 'https://rubygems.org'";
    echo "gem 'github-pages', group: :jekyll_plugins";
  } >Gemfile
script:
- bundle exec jekyll build
